#
# will merge this to bundled files
#
catalog:
  locations:
    # Local example organizational data
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]  
    # Local example systems
    - type: file
      target: /app/examples/systems.yaml
    # Local example clusters
    - type: file
      target: /app/examples/clusters.yaml

# local cluster (vkdr)
kubernetes:
  serviceLocatorMethod:
    type: 'singleTenant'
  clusterLocatorMethods:
    - type: 'localKubectlProxy'

permission:
  # disable if having issues with permissions
  enabled: true
  rbac:
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
      - kubernetes
