#
# Starts DevPortal with hot reloading and pretty logging:
#
# docker compose up --no-log-prefix
#
# Changes to dynamic-plugins.yaml will be processed into app-config running this:
#
# docker compose exec devportal /app/install-dynamic-plugins.sh /app/dynamic-plugins-root
#

services:
  devportal:
    image: veecode/devportal:latest
    ports:
      - "7007:7007"
    environment:
      - NODE_ENV=development
      # will use shell value
      - VEECODE_PROFILE=azure
      # AZURE/MS
      - AZURE_TENANT_ID
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_ORGANIZATION
      - AZURE_PROJECT
      - AZURE_TOKEN
    volumes:
      # dynamic plugins config (just enable/disable plugins)
      - ./dynamic-plugins.yaml:/app/dynamic-plugins.yaml:ro
