#
# will merge this to bundled files
#
catalog:
  locations:
    # Local example organizational data
    - type: url
      target: https://github.com/bancorocks/bancorocks-org-catalog/blob/main/catalog-info.yaml
      rules:
        - allow: [User, Group, Domain, System]

permission:
  # disable if having issues with permissions
  enabled: false
