#
# Starts DevPortal with Bitbucket Server (self-hosted) integration:
#
# docker compose up --no-log-prefix
#

services:
  devportal:
    image: veecode/devportal:latest
    ports:
      - "7007:7007"
    environment:
      - NODE_ENV=development
      # will use shell values
      - BITBUCKET_SERVER_HOST
      - BITBUCKET_SERVER_API_URL
      - BITBUCKET_SERVER_TOKEN
      # alternative: username/password authentication
      # - BITBUCKET_SERVER_USERNAME
      # - BITBUCKET_SERVER_PASSWORD
    volumes:
      # your config will add/override the default image config
      - ./app-config.yaml:/app/app-config.local.yaml:ro
      # dynamic plugins config (just enable/disable plugins)
      - ./dynamic-plugins.yaml:/app/dynamic-plugins.yaml:ro
